# Generated by Django 2.1.2 on 2018-10-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181029_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='quando',
            field=models.DateField(auto_now_add=True),
        ),
    ]
